# Generated by Django 2.0.5 on 2018-10-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_graphinput'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphinput',
            name='x',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='graphinput',
            name='y',
            field=models.CharField(max_length=200),
        ),
    ]
