# Generated by Django 2.0.5 on 2018-10-21 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20181019_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphinput',
            name='col',
            field=models.CharField(default='red', max_length=20),
            preserve_default=False,
        ),
    ]
