# Generated by Django 2.0.5 on 2018-10-21 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_graphinput_col'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='graphinput',
            name='col',
        ),
    ]
