# Generated by Django 2.1.2 on 2018-11-11 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20181021_1951'),
    ]

    operations = [
        migrations.DeleteModel(
            name='name',
        ),
        migrations.RenameField(
            model_name='graphoptions',
            old_name='col',
            new_name='color',
        ),
        migrations.AddField(
            model_name='graphoptions',
            name='type',
            field=models.CharField(default='red', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='graphinput',
            name='x',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='graphinput',
            name='y',
            field=models.IntegerField(),
        ),
    ]
