# Generated by Django 2.1.2 on 2018-11-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20181110_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphinput',
            name='x',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='graphinput',
            name='y',
            field=models.FloatField(),
        ),
    ]
