# Generated by Django 2.1.2 on 2018-11-18 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20181113_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphoptions',
            name='title',
            field=models.CharField(default='Title', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graphoptions',
            name='xlabel',
            field=models.CharField(default='x_label', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graphoptions',
            name='ylabel',
            field=models.CharField(default='y_label', max_length=50),
            preserve_default=False,
        ),
    ]
