# Generated by Django 2.1.2 on 2018-11-18 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20181117_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graphoptions',
            name='title',
        ),
        migrations.RemoveField(
            model_name='graphoptions',
            name='xlabel',
        ),
        migrations.RemoveField(
            model_name='graphoptions',
            name='ylabel',
        ),
        migrations.AddField(
            model_name='graphinput',
            name='title',
            field=models.CharField(default='titlt', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graphinput',
            name='xlabel',
            field=models.CharField(default='xlabel', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graphinput',
            name='ylabel',
            field=models.CharField(default='ylabel', max_length=50),
            preserve_default=False,
        ),
    ]
