# Generated by Django 2.1.2 on 2018-11-18 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20181117_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphLabels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('xlabel', models.CharField(max_length=50)),
                ('ylabel', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='graphinput',
            name='title',
        ),
        migrations.RemoveField(
            model_name='graphinput',
            name='xlabel',
        ),
        migrations.RemoveField(
            model_name='graphinput',
            name='ylabel',
        ),
    ]
