# Generated by Django 2.1.2 on 2018-11-18 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20181117_2136'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GraphLabels',
        ),
    ]
